# Generated by Django 5.0.4 on 2024-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название привычки')),
                ('goal', models.SmallIntegerField(verbose_name='Цель')),
                ('current_value', models.SmallIntegerField(verbose_name='Текущее значение')),
                ('status', models.CharField(choices=[('ac', 'active'), ('ar', 'archive'), ('dn', 'done'), ('dl', 'deleted'), ('no', 'None')], default='ac', max_length=20, verbose_name='статус привычки')),
            ],
        ),
        migrations.CreateModel(
            name='HabitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.SmallIntegerField(verbose_name='Текущее значение')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
