# Generated by Django 5.0.4 on 2024-05-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='status',
        ),
        migrations.AddField(
            model_name='habit',
            name='progress_status',
            field=models.CharField(choices=[('ac', 'active'), ('ar', 'archive'), ('dn', 'done'), ('dl', 'deleted'), ('no', 'None')], default='ac', max_length=20, verbose_name='Статус выполнения'),
        ),
        migrations.AddField(
            model_name='habit',
            name='repeat_period',
            field=models.CharField(choices=[('da', 'day'), ('we', 'week'), ('mo', 'month'), ('ye', 'year'), ('al', 'always')], default='ac', max_length=20, verbose_name='Статус выполнения'),
        ),
    ]
