# Generated by Django 5.0.4 on 2024-04-25 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='current_value',
            field=models.SmallIntegerField(verbose_name='Текущее значение'),
        ),
        migrations.AlterField(
            model_name='habbit',
            name='habbit_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='manage_hab.habbitgroup'),
        ),
        migrations.CreateModel(
            name='HabbitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.SmallIntegerField(verbose_name='Текущее значение')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('habbit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_hab.habbit', verbose_name='Привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
