# Generated by Django 5.0.4 on 2024-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0003_remove_habit_status_habit_progress_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='progress_status',
        ),
        migrations.AddField(
            model_name='habit',
            name='auth_type',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('always', 'always')], default='none', max_length=20, verbose_name='Тип авторизации'),
        ),
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archive', 'archive'), ('done', 'done'), ('deleted', 'deleted'), ('none', 'none')], default='active', max_length=20, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='repeat_period',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year'), ('always', 'always')], default='always', max_length=20, verbose_name='Период повтора'),
        ),
    ]
