# Generated by Django 5.0.4 on 2024-05-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0004_remove_habit_progress_status_habit_auth_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='auth_type',
        ),
    ]
