# Generated by Django 5.0.4 on 2024-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0007_alter_habbit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='status',
            field=models.CharField(choices=[('ac', 'active'), ('ar', 'archive'), ('dn', 'done'), ('dl', 'deleted'), ('no', 'None')], default='ac', max_length=20, verbose_name='статус привычки'),
        ),
    ]
