# Generated by Django 5.0.4 on 2024-05-20 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0008_alter_habbit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habbit',
            new_name='Habit',
        ),
        migrations.RenameModel(
            old_name='HabbitGroup',
            new_name='HabitGroup',
        ),
        migrations.RenameModel(
            old_name='HabbitProgress',
            new_name='HabitProgress',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='habbit_group',
            new_name='habit_group',
        ),
        migrations.RenameField(
            model_name='habitprogress',
            old_name='habbit',
            new_name='habit',
        ),
    ]
