# Generated by Django 5.0.4 on 2024-05-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0003_alter_habbit_current_value_alter_habbit_habbit_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habbit',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='habbitprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='habbit',
            name='status',
            field=models.CharField(choices=[('ac', 'active'), ('ar', 'archive'), ('dn', 'done'), ('dl', 'deleted')], default=None, max_length=20, verbose_name='статус привычки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habbit',
            name='habbit_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='manage_hab.habbitgroup', verbose_name='Группа привычки'),
        ),
        migrations.AlterField(
            model_name='habbit',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название привычки'),
        ),
    ]
