# Generated by Django 5.0.4 on 2024-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0004_remove_habbit_update_time_remove_habbitprogress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='status',
            field=models.CharField(choices=[('ac', 'active'), ('ar', 'archive'), ('dn', 'done'), ('dl', 'deleted'), ('no', 'None')], default=None, max_length=20, verbose_name='статус привычки'),
        ),
    ]
