# Generated by Django 5.0.4 on 2024-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hab', '0005_alter_habbit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='status',
            field=models.CharField(blank=True, choices=[('ac', 'active'), ('ar', 'archive'), ('dn', 'done'), ('dl', 'deleted'), ('no', 'None')], default=None, max_length=20, null=True, verbose_name='статус привычки'),
        ),
    ]
